# values.yaml

# Configuration de base
image:
  name: traefik
  tag: v3.3

# Activer le dashboard
dashboard:
  enabled: true

# Configuration des certificats Let's Encrypt
certificatesResolvers:
  cloudflare:
    acme:
      email: olivier@cloudstart.fr
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "8.8.8.8:53"
          - "1.1.1.1:53"

# Configuration du provider Cloudflare
providers:
  cloudflare:
    email: olivier@cloudstart.fr
    cloudflareAPIKey: e681e20205589b137a325beedfde5ca419049
    cloudflareAPIToken: CP7ww66lfTYZ_PonhumFmloXQlyEH__xziZRWUSn

# Configuration de l'entrée pour le dashboard
ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
      certResolver: cloudflare

# Configuration des annotations pour le dashboard
ingressRoute:
  dashboard:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    labels:
      app: traefik
    matchRule: Host(`traefik.cluster.exo7.cloud`)
    tls:
      certResolver: cloudflare
